version: 2
project_name: kure
before:
  hooks:
    - go mod download
    - go mod tidy
builds:
  -
    ldflags: -s -w -X main.version={{ .Tag }} -X main.commit={{ .ShortCommit }} -X main.date={{ .CommitDate }}
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    env:
        - CGO_ENABLED=0
    goos: 
      - darwin
      - linux
      - windows
      - freebsd
      - openbsd
    goarch: 
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
archives:
  -
    name_template: '{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
checksum:
  name_template: '{{ .ProjectName }}_{{ .Tag }}_checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'typo'
      - 'Merge pull request'
      - 'Merge branch'

homebrew_casks:
  - 
    repository:
      owner: GGP1
      name: homebrew-tap
    directory: Casks
    homepage: https://github.com/GGP1/kure
    description: Cross-platform CLI password manager with sessions
    license: Apache 2.0

scoops:
  -
    repository:
      owner: GGP1
      name: scoop-bucket
    homepage:  https://github.com/GGP1/kure
    description: Cross-platform CLI password manager with sessions
    license: Apache 2.0

nfpms:
- 
  formats:
    - deb
  maintainer: GGP1
  description: Cross-platform CLI password manager with sessions
  homepage: https://github.com/GGP1/kure
  license: Apache 2.0
  file_name_template: '{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
