FROM golang:1.17.6-alpine3.15 as builder

WORKDIR /kure

COPY go.mod .

RUN go mod download && go mod verify

RUN apk add --update --no-cache git make

COPY . .

RUN make install

# ---------------------------------------------

FROM alpine:3.15.0

ENV USER=gandalf
ENV UID=10001

COPY --from=builder /go/bin/kure /usr/bin/

RUN adduser $USER -D -g "" -s "/sbin/nologin" -u $UID \
    && chown $USER /usr/bin/kure \
    && chmod 0700 /usr/bin/kure

USER $USER

CMD ["/usr/bin/kure"]