project_name: kure_v1_migration
builds:
  -
    ldflags: -s -w -X main.version={{ .Version }} -X main.commit={{ .ShortCommit }} -X main.date={{ .CommitDate }}
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    env:
        - CGO_ENABLED=0
    goos: 
      - darwin
      - linux
      - windows
      - freebsd
      - openbsd
    goarch: 
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
archives:
  -
    name_template: '{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: '{{ .ProjectName }}_{{ .Tag }}_checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'typo'
      - 'Merge pull request'
      - 'Merge branch'
