// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.0
// 	protoc        v3.20.1
// source: pb/names.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Names struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Map map[string][]byte `protobuf:"bytes,1,rep,name=map,proto3" json:"map" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Names) Reset() {
	*x = Names{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_names_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Names) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Names) ProtoMessage() {}

func (x *Names) ProtoReflect() protoreflect.Message {
	mi := &file_pb_names_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Names.ProtoReflect.Descriptor instead.
func (*Names) Descriptor() ([]byte, []int) {
	return file_pb_names_proto_rawDescGZIP(), []int{0}
}

func (x *Names) GetMap() map[string][]byte {
	if x != nil {
		return x.Map
	}
	return nil
}

var File_pb_names_proto protoreflect.FileDescriptor

var file_pb_names_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x62, 0x2f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x22, 0x65, 0x0a, 0x05, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x24, 0x0a,
	0x03, 0x6d, 0x61, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x03,
	0x6d, 0x61, 0x70, 0x1a, 0x36, 0x0a, 0x08, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x19, 0x5a, 0x17, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x47, 0x47, 0x50, 0x31, 0x2f, 0x6b,
	0x75, 0x72, 0x65, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_names_proto_rawDescOnce sync.Once
	file_pb_names_proto_rawDescData = file_pb_names_proto_rawDesc
)

func file_pb_names_proto_rawDescGZIP() []byte {
	file_pb_names_proto_rawDescOnce.Do(func() {
		file_pb_names_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_names_proto_rawDescData)
	})
	return file_pb_names_proto_rawDescData
}

var file_pb_names_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_names_proto_goTypes = []interface{}{
	(*Names)(nil), // 0: pb.Names
	nil,           // 1: pb.Names.MapEntry
}
var file_pb_names_proto_depIdxs = []int32{
	1, // 0: pb.Names.map:type_name -> pb.Names.MapEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_names_proto_init() }
func file_pb_names_proto_init() {
	if File_pb_names_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_names_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Names); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_names_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_names_proto_goTypes,
		DependencyIndexes: file_pb_names_proto_depIdxs,
		MessageInfos:      file_pb_names_proto_msgTypes,
	}.Build()
	File_pb_names_proto = out.File
	file_pb_names_proto_rawDesc = nil
	file_pb_names_proto_goTypes = nil
	file_pb_names_proto_depIdxs = nil
}
